### ISSUE TITLE
[Bug 0.8.6] Erreur lors de la génération du fichier pour la NAF

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#107]
Lorsque je tente de générer l'export pour la naf, j'ai un fichier incomplet. En effet, je n'ai que les coaches mais pas les matches.
En pj le fichier tourma et l'export
De plus, j'ai l'erreur suivante :
`
D:\privé - cle\bb\LuteceCup2016>call "C:\Program Files (x86)\Java\jre7\bin\java.exe" -jar TourMa.0.8.6.jar
Can't find resource for bundle java.util.PropertyResourceBundle, key YYYY-MM-dd HH:MM
Exception in thread "AWT-EventQueue-0" java.lang.ClassCastException: tourma.data.Team cannot be cast to tourma.data.Coach
        at tourma.data.Tournament.exportNAF(Tournament.java:1170)
        at tourma.MainFrame.jmiExportActionPerformed(MainFrame.java:1010)
        at tourma.MainFrame.access$700(MainFrame.java:92)
        at tourma.MainFrame$7.actionPerformed(MainFrame.java:425)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)`

**Comment by Bojo38** [comment]
Je ne vois pas la pièce jointe. Peux-tu me zipper le fichier du tournoi et me l'envoyer STP ?

**Comment by Funny-Valentine** [comment]
[NAFLuteceCup2016.zip](https://github.com/Bojo38/tourma/files/359415/NAFLuteceCup2016.zip)

**Comment by Funny-Valentine** [comment]
Oups, désolé.

      De : Bojo <notifications@github.com>
 À : Bojo38/tourma <tourma@noreply.github.com> 
Cc : Funny-Valentine <mailgoog-funny@yahoo.fr>; Author <author@noreply.github.com>
 Envoyé le : Mardi 12 juillet 2016 14h54
 Objet : Re: [Bojo38/tourma] [Bug 0.8.6] Erreur lors de la génération du fichier pour la NAF (#107)
   
Je ne vois pas la pièce jointe. Peux-tu me zipper le fichier du tournoi et me l'envoyer STP ?—

**Comment by Bojo38** [comment]
L'anomalie a été corrigée. Il y avait une erreur mineur sur l'heure et une majeure sur l'export des matches. Les matchs n'étaient pas exportés si c'était des matchs par équipe. L'anomalie est corrigée en developpement et sera intégrée à la prochaine livraison
