### ISSUE TITLE
[0.8.2a] tournoi par équipe - Pas de génération de la seconde ronde

### ISSUE THREAD

**Issue by Funny-Valentine** [Bojo38/tourma#69]
Impossible de généré un second round pour un tournoi en équipe.
Fichier xml du tournoi envoyé par mail.

**Comment by Bojo38** [comment]
Je ne parviens pas à reproduire le problème, peut-être un problème de mémoire.

Il faudrait lancer la commande dans un terminal: "java -jar tourma.jar" et me redonner le résultat.

**Comment by Funny-Valentine** [comment]
voilà le résultat :

D:\privé - cle\bb\perso_tourma>call "C:\Program Files (x86)\Java\jre7\bin\java.exe" -jar TourMa.jar
Exception in thread "AWT-EventQueue-0" java.util.MissingResourceException: Can't find resource for bundle java.util.PropertyResourceBundle, key Animation
        at java.util.ResourceBundle.getObject(Unknown Source)
        at java.util.ResourceBundle.getObject(Unknown Source)
        at java.util.ResourceBundle.getString(Unknown Source)
        at tourma.languages.Translate.translate(Translate.java:70)
        at tourma.MainFrame.jmiGenerateNextRoundActionPerformed(MainFrame.java:1653)
        at tourma.MainFrame.access$2100(MainFrame.java:85)
        at tourma.MainFrame$21.actionPerformed(MainFrame.java:546)
        at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
        at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
        at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
        at javax.swing.AbstractButton.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
        at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
        at java.awt.Component.processMouseEvent(Unknown Source)
        at javax.swing.JComponent.processMouseEvent(Unknown Source)
        at java.awt.Component.processEvent(Unknown Source)
        at java.awt.Container.processEvent(Unknown Source)
        at java.awt.Component.dispatchEventImpl(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
        at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
        at java.awt.Container.dispatchEventImpl(Unknown Source)
        at java.awt.Window.dispatchEventImpl(Unknown Source)
        at java.awt.Component.dispatchEvent(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$200(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.awt.EventQueue$4.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$1.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

La version de java utilisé : java version "1.7.0_51"
Java(TM) SE Runtime Environment (build 1.7.0_51-b13)
Java HotSpot(TM) Client VM (build 24.51-b03, mixed mode, sharing)

J'ai renvoyé par mail le fichier tourma xml corrigé.

**Comment by Bojo38** [comment]
OK, je pense savoir ce que c'est. J'essaye de faire une 0.8.3 d'ici ce week-end
